apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zjq86o3jl-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:5b5d4f3e473eb775fa0384dc56541d24ebad2993@sha256:2267c4dcc8f17d648b83084e6b243e6c65b8959c69655adf17707bf6a9e3e019
          name: container-image
