apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zjq86o3jl-python
  janus-idp.io/tekton: zjq86o3jl-python
  backstage.io/kubernetes-id: zjq86o3jl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zjq86o3jl-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
